server:
  port: 8080
spring:
  application:
    name: metal_filament_inspection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.160.220:3306/metal_filament_inspection?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Zzh123456
  data:
    redis:
      host: 121.40.160.220
      port: 6379
      password: Zzh123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  rabbitmq:
    host: 121.40.160.220 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /wirematerial # 虚拟主机
    username: kunpeng # 用户名
    password: Zzh123456? # 密码
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 3
          stateless: false
mybatis-plus:
  type-aliases-package: com.kunpeng.metal_filament_inspection.domain # 别名扫描包
logging:
  level:
    com:
      kunpeng:
        metal_filament_inspection: debug
jwt:
  secret: "mental_filament_inspection_backend_jwt_secret_key_2026_kunpeng"
  expiration: 7200000
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.kunpeng.metal_filament_inspection.controller
huawei:
  iot:
    amqp:
      host: amqps://f09fb0e0e6.st1.iotda-app.cn-east-3.myhuaweicloud.com  # 接入地址
      port: 5671
      access-key: "fjbhveXV"
      access-code: "xRkCW3g6ZUJ4zDiL8CeAfnSislpvy86M"
      queue-name: "DefaultQueue"
      client-id: "backend-${random.uuid}" # 客户端唯一标识
      auto-acknowledge: true
    app:
      ak: "HPUA69LJ2GT1NKLAEMS9"
      sk: "QAocumBao0UyRrKtRCYdxXZ1O4ToPZi5QseDeXH0"
      endpoint: "f09fb0e0e6.st1.iotda-app.cn-east-3.myhuaweicloud.com"
      projectId: "019e966a305f765cb9bd8e6b650effc1"
yolo:
  model-path: src/main/resources/models/best.onnx
  confidence-threshold: 0.5
  nms-threshold: 0.4
  input-width: 640
  input-height: 640
  image-dir: "src/main/resources/textPicture"
# 七牛云存储配置
qiniu:
  access-key: "VbN_icwnxdmV1ZADAAi3fH_SQUn8Czyv5_TpbDH1"
  secret-key: "-FRoyL9QtL5_j7Q_naMylGSVCSNtb6iMA3JNKBmF"
  bucket: "metalfilamentinspection"
  domain: "th8lfohjy.hn-bkt.clouddn.com"
  region: "guangdong"
  expire-seconds: 3600
  use-https: false
opencv:
  library-path: "D:/opencv/build/java/x64/opencv_java4120.dll"